export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_NEW_RELEASES_ALBUMS = 'UPDATE_NEW_RELEASES_ALBUMS';
export const UPDATE_CURRENT_USER_SAVED_ALBUMS = 'UPDATE_CURRENT_USER_SAVED_ALBUMS';
export const UPDATE_CURRENT_USER_SAVED_TRACKS = 'UPDATE_CURRENT_USER_SAVED_TRACKS';
export const SET_VALUE_ARTISTS_SEARCH = 'SET_VALUE_ARTISTS_SEARCH';
